### ISSUE TITLE
The load_dataset.py is lost 

### ISSUE THREAD

**Issue by xtyi1997** [Z-GCNETs/Z-GCNETs#1]
error ModuleNotFoundError: No module named 'load_dataset'
can you upload it in your convenience

**Comment by Z-GCNETs** [comment]
Hello, I have upload the load_dataset.py file and also updated the code \& data.

**Comment by Z-GCNETs** [comment]
> error ModuleNotFoundError: No module named 'load_dataset'
> can you upload it in your convenience

Hello, we have uploaded the load_dataset.py and also updated code \& datasets.
